# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 426403eefd6de27ca5e1478ccb83941ad370e661388de0261b094bba2e6e34e033838a469c087089834d1a0a58466fccb6e927538d0e796482620ec512d68aff

test:
  secret_key_base: 073637ab8c0cb004ffb33348784884a82d5f9feea1e3a294a60ce05a1a06f85c61d911d27f61239ca5abb0353d97672da7f160e90893fe813bc50ae60f8e1bef

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
